
services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: krishna
      POSTGRES_PASSWORD: 458336
      POSTGRES_DB: Ecom
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always


volumes:
  postgres-data:

